<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DrivingLicence.Worker-238c06b9-cb6a-4c43-b933-6944cda80900</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DrivingLicence.Domain\DrivingLicence.Domain.csproj" />
    <ProjectReference Include="..\DrivingLicence.Infrastructure\DrivingLicence.Infrastructure.csproj" />
    <ProjectReference Include="..\DrivingLicence.ServiceDefaults\DrivingLicence.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
